describe('Current test', () => {
    // it doesn't work because of the fakepay website: reference is required
    // it('Checks if betaling works (succes)', () => {
    //     //cy.visit('https://salmon-smoke-00d5f3d03.2.azurestaticapps.net/Login')
    //     cy.visit('http://localhost:3000/Login')
    //     cy.get('#username').type('Gebruiker')
    //     cy.get('#password').type('GebruikerW1!')
    //     cy.contains('Log in').click()
    //     cy.contains('U bent ingelogd')

    //     //cy.visit('https://salmon-smoke-00d5f3d03.2.azurestaticapps.net/Programma')
    //     cy.visit('http://localhost:3000/Programma')
    //     cy.contains('bestel').click()
    //     cy.get('#SelectedRang').select('Rang 1')
    //     cy.get('#NumberTickets').type('1')
    //     cy.get('.btn').click()
    //     cy.wait(1000)
    //     cy.url().should('include', '/Winkelmand')
    //     cy.contains('1')
    //     cy.get('input').type('Cypress@Cypress2.com')
    //     cy.get('.btn').click()
    //     cy.origin('https://fakepay.azurewebsites.net', () => {
    //     cy.get('#account').type('NL55ABNA5660751954')
    //     cy.contains('Betaal').click()	
    //     })
    //     cy.contains('Betaling gelukt').should('be.visible')
    // })

        // it('Checks if betaling works (failed)', () => {
    //     //cy.visit('https://salmon-smoke-00d5f3d03.2.azurestaticapps.net/Login')
    //     cy.visit('http://localhost:3000/Login')
    //     cy.get('#username').type('Gebruiker')
    //     cy.get('#password').type('GebruikerW1!')
    //     cy.contains('Log in').click()
    //     cy.contains('U bent ingelogd')

    //     //cy.visit('https://salmon-smoke-00d5f3d03.2.azurestaticapps.net/Programma')
    //     cy.visit('http://localhost:3000/Programma')
    //     cy.contains('bestel').click()
    //     cy.get('#SelectedRang').select('Rang 1')
    //     cy.get('#NumberTickets').type('1')
    //     cy.get('.btn').click()
    //     cy.wait(1000)
    //     cy.url().should('include', '/Winkelmand')
    //     cy.contains('1')
    //     cy.get('input').type('Cypress@Cypress2.com')
    //     cy.get('.btn').click()
    //     cy.origin('https://fakepay.azurewebsites.net', () => {
    //     cy.get('#account').type('CYPRESSBANKING1234')
    //     cy.contains('Betaal').click()	
    //     })
    //     cy.contains('Betaling gelukt').should('be.visible')
    // })
})