name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.5
        with:
          build: npm run build
          start: npm start